planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0

fr3_arm:
  planner_configs:
    - RRTConnectkConfigDefault

fr3_hand:
  planner_configs:
    - RRTConnectkConfigDefault
